/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import conexao_bd.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tipos.*;

/**
 *
 * @author Bernardes
 */
public class pesquisaAvancada extends javax.swing.JFrame {
    
    Conexao conecta = new Conexao();
    Gerente gerente = new Gerente();
    Cliente cliente = new Cliente();
    public int y = 0;

    /**
     * Creates new form pesquisaAvancada
     */
    public pesquisaAvancada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPesquisaPorCpf = new javax.swing.JTextField();
        jButtonClientes = new javax.swing.JButton();
        jButtonGerentes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Pesquisar cliente por CPF:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 21, -1, -1));
        getContentPane().add(jPesquisaPorCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 224, -1));

        jButtonClientes.setText("Todos Clientes");
        jButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 58, 109, -1));

        jButtonGerentes.setText("Todos Gerentes");
        jButtonGerentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerentesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGerentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 99, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 359, 208));

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_itau.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 290));

        jMenu1.setText("File");

        jMenuItem1.setText("Voltar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sair");

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesActionPerformed
        conecta.conecta();
        String sql = "SELECT * FROM cliente";
        String[][] resultado = new String[50][10];
        ResultSet rs = conecta.executarSql2(sql);
        try {
            rs.first();
            int i2 = 0;
            
            do {
                resultado[i2][0] = String.valueOf(rs.getInt("cod_cliente"));
                resultado[i2][1] = rs.getString("nome_cliente");
                resultado[i2][2] = rs.getString("end_rua");
                resultado[i2][3] = String.valueOf(rs.getInt("end_numero"));
                resultado[i2][4] = rs.getString("end_cidade");
                resultado[i2][5] = rs.getString("end_estado");
                resultado[i2][6] = String.valueOf(rs.getInt("cpf_cliente"));
                resultado[i2][7] = String.valueOf(rs.getInt("rg_cliente"));
                resultado[i2][8] = rs.getString("email_cliente");
                resultado[i2][9] = rs.getString("senha_cliente");
                
                i2++;
            } while (rs.next());
            y = 0;
            jTextArea1.setText("");
            jTextArea1.append("Cod_Cliente  Nome  Rua  Numero  Cidade  Estado  CPF  RG  Email  Senha \n");
            
            for (int i = 0; i < resultado.length; i++) {
                if (resultado[i][y] == null) {
                    break;
                }
                for (int y = 0; y <= 9; y++) {
                    
                    jTextArea1.append(resultado[i][y] + "  ");
                    this.y = y;
                }
                
                jTextArea1.append("\n");
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(pesquisaAvancada.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_jButtonClientesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaGerente telaGerente = new TelaGerente();
        telaGerente.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButtonGerentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerentesActionPerformed
        conecta.conecta();
        String sql = "SELECT * FROM gerente_conta";
        String[][] resultado = new String[50][4];
        ResultSet rs = conecta.executarSql2(sql);
        try {
            rs.first();
            int i2 = 0;
            
            do {
                resultado[i2][0] = String.valueOf(rs.getInt("cod_gerente"));
                resultado[i2][1] = rs.getString("nome_gerente");
                resultado[i2][2] = rs.getString("cpf_gerente");
                resultado[i2][3] = rs.getString("senha_gerente");
                
                i2++;
            } while (rs.next());
            
            y = 0;
            jTextArea1.setText("");
            
            jTextArea1.append("Cod_Cliente  Nome  CPF  Senha \n");
            
            for (int i = 0; i < resultado.length; i++) {
                if (resultado[i][y] == null) {
                    break;
                }
                for (int y = 0; y <= 3; y++) {
                    
                    jTextArea1.append(resultado[i][y] + "  ");
                    this.y = y;
                }
                
                jTextArea1.append("\n");
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(pesquisaAvancada.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGerentesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Cliente resultado = new Cliente();
        BD_Cliente control_cliente = new BD_Cliente();
        cliente.SetCpf(Integer.parseInt(jPesquisaPorCpf.getText()));
        resultado = control_cliente.pesquisarPorCpf(cliente);
        jTextArea1.setText("");
        jTextArea1.append(resultado.getCodigo() + " " + resultado.getNome() + " " + resultado.getRua() + " " + resultado.getNum() + " " + resultado.getCidade() + " " + resultado.getEstado() + " " + resultado.getCpf() + " " + resultado.getRg() + " " + resultado.getEmail() + " " + resultado.getSenha());
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pesquisaAvancada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pesquisaAvancada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pesquisaAvancada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pesquisaAvancada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pesquisaAvancada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonGerentes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jPesquisaPorCpf;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
