/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import conexao_bd.*;
import javax.swing.JOptionPane;
import tipos.*;
/**
 *
 * @author Bernardes
 */
public class TelaLogin extends javax.swing.JFrame {
    // variaveis que serao usadas em toda classe
       Conexao conexao = new Conexao();
       BD_Gerente control_gerente = new BD_Gerente();
       Gerente gerente = new Gerente();
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        
        initComponents();
        conexao.conecta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUsuario = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jTextUsuario = new javax.swing.JTextField();
        jButtonAcessar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jRadioGerente = new javax.swing.JRadioButton();
        jRadioCliente = new javax.swing.JRadioButton();
        jLabelTexto1 = new javax.swing.JLabel();
        jLabelTexto2 = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jPasswordSenha = new javax.swing.JPasswordField();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelUsuario.setText("Usuário:");
        getContentPane().add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 80, -1));

        jLabelSenha.setText("Senha:");
        getContentPane().add(jLabelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 40, -1));

        jTextUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 110, -1));

        jButtonAcessar.setText("Acessar");
        jButtonAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcessarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAcessar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 80, -1));

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 80, -1));

        jRadioGerente.setText("Gerente Conta");
        jRadioGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioGerenteActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 100, -1));

        jRadioCliente.setText("Pessoa Fisica/Juridica");
        getContentPane().add(jRadioCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 130, -1));

        jLabelTexto1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTexto1.setText("Você é: (caso seja Pessoa Fisica/Jurica e queira ");
        getContentPane().add(jLabelTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 300, 14));

        jLabelTexto2.setText("se cadastrar, selecione campo Pessoa Fisica, e clique em Acessar)");
        getContentPane().add(jLabelTexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 320, -1));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/itau_logo_1.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 200, 230));

        jPasswordSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 110, -1));

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_itau.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 680, 360));
        jLabelFundo.getAccessibleContext().setAccessibleName("jLabelFundo");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUsuarioActionPerformed

    private void jButtonAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcessarActionPerformed
        //verifica qual jRadio está selecionado, se for o do usuario Pessoa Fisica ou Juridica
        // não é necessario colocar usuario e senha já que será um novo cadastro
        //caso selecione Gerente de Conta, é necessario usuario e senha para logar no sistema
        TelaUsuario telaUsuario = new TelaUsuario();
        TelaGerente telaGerente = new TelaGerente();
        if (jRadioCliente.isSelected()){
            telaUsuario.setVisible(true);
            dispose();
        }
        if (jRadioGerente.isSelected()){
            gerente.SetCodigo(Integer.parseInt(jTextUsuario.getText()));
            String senha = String.valueOf(jPasswordSenha.getPassword());
            gerente.SetSenha(senha);
            //verifica se cadastro de gerente existe
            if (control_gerente.verificaGerente(gerente)){
                telaGerente.setVisible(true);
                JOptionPane.showMessageDialog(null, "Login de Gerente com sucesso!");
                dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Gerente não encontrado");
            }
            
        }
    }//GEN-LAST:event_jButtonAcessarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
       conexao.desconecta();
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jRadioGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioGerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioGerenteActionPerformed

    private void jPasswordSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcessar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelTexto1;
    private javax.swing.JLabel jLabelTexto2;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField jPasswordSenha;
    private javax.swing.JRadioButton jRadioCliente;
    private javax.swing.JRadioButton jRadioGerente;
    private javax.swing.JTextField jTextUsuario;
    // End of variables declaration//GEN-END:variables
}
